channels:
- conda-forge
dependencies:
- breathe
- cmake
- doxygen
- furo
- gmattensor >=0.10.1
- h5py
- ninja
- numpy
- pybind11
- python
- python-gmattensor >0.9.0
- scikit-build
- setuptools_scm
- sphinx
- sphinx-tabs
- sphinx_rtd_theme
- xtensor >=0.24.2
- xtensor-python
