channels:
  - conda-forge
dependencies:
  - catch2
  - cmake
  - doxygen
  - gmattensor
  - goosefem
  - h5py
  - mathjax
  - ninja
  - numpy
  - pybind11
  - python
  - scikit-build
  - setuptools_scm
  - xtensor
  - xtensor-python
